# This is a basic workflow to help you get started with Actions

name: first pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: date
      - name: Repo
        run: |
         echo "Repo: ${{ github.repository}}"
